server:
  port: 8880

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud.gateway: 'TRACE'   
  
spring:
  profiles: docker
